services:
  api:
    container_name: pavas-api
    build:
      context: .
      target: ${TARGET:-development}
    restart: unless-stopped
    init: true
    env_file:
      - .env
    ports:
      - "8000:3000"
    networks:
      - pavas-network

networks:
  pavas-network:
    driver: bridge
